name: Run Testim Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  testim:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Testim CLI
        run: npm install -g @testim/testim-cli

      - name: Run Testim Tests
        env:
          TESTIM_TOKEN: Kr5tvpz5sJ6cSqmGiKtd6h1BFdJbwKkVVaWvGLh4MMvWA1lbFv
        run: |
          testim --token "Kr5tvpz5sJ6cSqmGiKtd6h1BFdJbwKkVVaWvGLh4MMvWA1lbFv" --project "Uq2fzwleotK72p7DjH69" --grid "Testim-Grid" --mode "extension" --branch "master"
